### ISSUE TITLE
talker_dio_logger exception when hot reloading: Addon currently exist

### ISSUE THREAD

**Issue by thedotedge** [Frezyx/talker#102]
**Describe the bug**
talker_dio_logger interceptor crashes when app is hot reloaded.

**To Reproduce**

1. Talker deps:

```
  talker: ^2.4.0
  talker_flutter: ^2.4.1
  talker_dio_logger: ^1.3.0
```

2. Set up Talker as singleton:

```dart
import 'package:talker_flutter/talker_flutter.dart';

class Logger {
  Logger._();

  static final instance = TalkerFlutter.init();
}
```

3. Register dio interceptor:

```dart
dio.interceptors.add(
      TalkerDioLogger(
        talker: Logger.instance,
        settings: const TalkerDioLoggerSettings(
          printRequestHeaders: true,
          printResponseHeaders: true,
          printResponseMessage: false,
        ),
      ),
    );
```

4. Initial run works fine, however, any hot reload crashes with the following error:

```
======== Exception caught by widgets library =======================================================
The following _Exception was thrown building Builder(dirty, dependencies: [_LocalizationsScope-[GlobalKey#05c0e]]):
Exception: Addon currently exist

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/oleg/Projects/app/lib/main.dart:85:34
When the exception was thrown, this was the stack: 
#0      Talker.registerAddon (package:talker/src/talker.dart:306:7)
#1      new TalkerDioLogger (package:talker_dio_logger/talker_dio_logger_interceptor.dart:18:13)
#2      new Api (package:app/services/api.dart:26:7)
#3      new TokenApi (package:app/services/token_api.dart:10:35)
#4      AppRouter.router.<anonymous closure> (package:app/navigation/app_router.dart:58:34)
#5      RouteBuilder._buildPageForRoute (package:go_router/src/builder.dart:297:27)
#6      RouteBuilder._buildRecursive (package:go_router/src/builder.dart:184:34)
#7      RouteBuilder.buildPages (package:go_router/src/builder.dart:143:7)
```

**Expected behavior**
Hot reload would happen without any issues.

**Smartphone:**
 - Device: iPhone 14 simulator
 - OS: iOS 16.2 

Same issue happens in latest Chrome on Mac OS.

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 12.6.3 21G419 darwin-arm64, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by Frezyx** [comment]
Resolved in [3.0.0 Release](https://github.com/Frezyx/talker/pull/108)
Please reopen the issue if you have any further questions or if the bug has not been fixed ❤️
