### ISSUE TITLE
Button "Share logs file" => Error. Error Talker Wrapper. 

### ISSUE THREAD

**Issue by Callemul** [Frezyx/talker#257]
I don`t have folder /data/data/**com.example.spez_bud**(default folder when App is installed).
- this is an emulator (Android API 30)
I think this is why an error.

**Describe the bug**

**To Reproduce**
1. Go to **TalkerScreen** Page
`Navigator.of(context).push(
                          MaterialPageRoute(
                            builder: (context) => TalkerScreen(talker: talker),
                          )
                      );`
2. Click on three lines button (menu button), at the right corner
3. Click on "Share logs file" Button
4. Error

`talker_flutter: ^4.4.0`

```
E/flutter (11483): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Share failed, Failed to find configured root that contains /data/data/com.example.spez_bud/cache/share_plus/talker_logs_2024-08-28 21 23 53.935457.txt, java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.example.spez_bud/cache/share_plus/talker_logs_2024-08-28 21 23 53.935457.txt
E/flutter (11483): 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:867)
E/flutter (11483): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:467)
E/flutter (11483): 	at dev.fluttercommunity.plus.share.Share.getUrisForPaths(Share.kt:188)
E/flutter (11483): 	at dev.fluttercommunity.plus.share.Share.shareFiles(Share.kt:96)
E/flutter (11483): 	at dev.fluttercommunity.plus.share.MethodCallHandler.onMethodCall(MethodCallHandler.kt:46)
E/flutter (11483): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter (11483): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter (11483): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (11483): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (11483): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (11483): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (11483): 	at android.os.Looper.loop(Looper.java:223)
E/flutter (11483): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (11483): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11483): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (11483): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (11483): , null)
E/flutter (11483): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (11483): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (11483): <asynchronous suspension>
E/flutter (11483): #2      MethodChannelShare.shareXFiles (package:share_plus_platform_interface/method_channel/method_channel_share.dart:108:20)
E/flutter (11483): <asynchronous suspension>
E/flutter (11483): #3      downloadFile (package:talker_flutter/src/utils/download_logs/download_nonweb_logs.dart:13:3)
E/flutter (11483): <asynchronous suspension>
E/flutter (11483): #4      TalkerViewController.downloadLogsFile (package:talker_flutter/src/controller/talker_view_controller.dart:67:55)
E/flutter (11483): <asynchronous suspension>
E/flutter (11483): #5      _TalkerViewState._shareLogsInFile (package:talker_flutter/src/ui/talker_view.dart:215:5)
E/flutter (11483): <asynchronous suspension>
E/flutter (11483): 
```

**Comment by Frezyx** [comment]
Hello @Callemul ! 
Please explain on which device did you try to perform this action and is the error being repeated now?

**Comment by Callemul** [comment]
sorry, the problem is not actualy now. Don`t need check "is it solved"... But Your library very useful for us in Terminal for us!
