### ISSUE TITLE
Cannot share a log on iPad

### ISSUE THREAD

**Issue by justjew** [Frezyx/talker#265]
**Describe the bug**
`share_plus` package requires providing `Rect? sharePositionOrigin` when using on iPad.
So I cannot share a log file from iPad.

**To Reproduce**
1. Run on iPad
2. Open TalkerScreen
3. Press "Share logs file"
4. See the exception

```
[exception] | 11:46:34 619ms | Uncaught app exception
PlatformException(error, sharePositionOrigin: argument must be set, {{0, 0}, {0, 0}} must be non-zero and within coordinate space of source view: {{0, 0}, {1080, 810}}, null, null)
StackTrace: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      MethodChannelShare.shareXFiles (package:share_plus_platform_interface/method_channel/method_channel_share.dart:112:20)
<asynchronous suspension>
#3      downloadFile (package:talker_flutter/src/utils/download_logs/download_nonweb_logs.dart:13:3)
<asynchronous suspension>
#4      TalkerViewController.downloadLogsFile (package:talker_flutter/src/controller/talker_view_controller.dart:67:55)
<asynchronous suspension>
#5      _TalkerViewState._shareLogsInFile (package:talker_flutter/src/ui/talker_view.dart:215:5)
<asynchronous suspension>
}
```

**Expected behavior**
An ability to provide Rect into e.g. `TalkerScreenTheme`

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iPadOS 17.4

**Comment by makon** [comment]
This is due to the missing `sharePositionOrigin` paramter when using [`Share.shareXFiles(...)`](https://github.com/Frezyx/talker/blob/769bbdcf6a51258f1d6463e9f6263d8a05b5dfd6/packages/talker_flutter/lib/src/utils/download_logs/download_logs_native.dart#L13C3-L13C54)

As share_plus states it [here](https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus#ipad) the `sharePositionOrigin` paramter is necessary for iPads

> share_plus requires iPad users to provide the sharePositionOrigin parameter.
> Without it, share_plus will not work on iPads and may cause a crash or letting the UI not responding.

In the function [docs](https://pub.dev/documentation/share_plus/latest/share_plus/Share/shareXFiles.html) it is mentioned that the param has no effect on other devices. 
> The optional sharePositionOrigin parameter can be used to specify a global origin rect for the share sheet to popover from on iPads and Macs. It has no effect on other devices.

One possible fix is to modify the `downloadFile` function to accept a `BuildContext` as a second parameter and handle the `sharePositionOrigin` parameter there. This change would also require adjustments to `download_logs_html` and `download_logs_web` to accommodate the new `BuildContext` parameter.

I could create a PR if this solution is fine for you or if you have alternative suggestions for resolving this issue.
