### ISSUE TITLE
Unsupported operation: Cannot add to an unmodifiable list

### ISSUE THREAD

**Issue by ProjectAJ14** [Frezyx/talker#84]
**Describe the bug**
Issue while adding any filter in the TalkerScreen 

**To Reproduce**
1. Go to TalkerScreen
2. Click on any filter

**Expected behavior**
The filters should be added without errors

**Additional context**
```
Unsupported operation: Cannot add to an unmodifiable list

When the exception was thrown, this was the stack: 
#0      UnmodifiableListMixin.add (dart:_internal/list.dart:114:5)
#1      TalkerScreenController.addFilterTitle (package:talker_flutter/src/controller/talker_screen_controller.dart:57:56)
#2      TalkerScreenFilter._onToggleTitle (package:talker_flutter/src/ui/widgets/filter/talker_screen_filter.dart:167:18)
#3      TalkerScreenFilter.build.<anonymous closure> (package:talker_flutter/src/ui/widgets/filter/talker_screen_filter.dart:115:23)
#4      _GroupButtonBodyState._generateButtonsList.<anonymous closure> (package:group_button/src/group_button_body.dart:170:38)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#18     _invoke1 (dart:ui/hooks.dart:167:13)
#19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#13c3e
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(44.3, 280.0)
  finalLocalPosition: Offset(34.3, 21.0)
  button: 1
  sent tap down
====================================================================================================
```

**Comment by Frezyx** [comment]
Hello @ProjectAJ14 ! 
I see this issue. I will fix it in next release!

**Comment by Frezyx** [comment]
You can contribute If you know how to fix it

**Comment by ProjectAJ14** [comment]
Hello @Frezyx , I have added a [PR#85](https://github.com/Frezyx/talker/pull/85)
